# Generated by Django 3.2.9 on 2021-11-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='poster',
            field=models.ImageField(null=True, upload_to='movie/images'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='video',
            field=models.FileField(null=True, upload_to='movie/videos'),
        ),
    ]
