# Generated by Django 3.2.9 on 2021-11-07 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20211107_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='video',
        ),
    ]
