# Generated by Django 3.2.9 on 2021-11-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20211107_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='first_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
