# Generated by Django 3.2.9 on 2021-11-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20211109_0937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ('first_name',), 'verbose_name': 'cast'},
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'ordering': ('name',), 'verbose_name': 'movies', 'verbose_name_plural': 'movies'},
        ),
        migrations.AlterField(
            model_name='actor',
            name='profile_image',
            field=models.ImageField(upload_to='actor/images'),
        ),
    ]
