# Generated by Django 3.2.9 on 2021-11-09 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20211109_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('category_name',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
