# Generated by Django 3.2.9 on 2021-11-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='actors',
            field=models.ManyToManyField(to='movies.Actor'),
        ),
    ]
